env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - warn
  comma-dangle:
    - 0
  react/jsx-uses-vars:
    - 1
  react/display-name:
    - 1